apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-cicd-app
  template:
    metadata:
      labels:
        app: simple-cicd-app
    spec:
      containers:
      - name: simple-cicd-app
        image: anugrahamanoharan16-creator/simple-cicd-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-cicd-service
spec:
  selector:
    app: simple-cicd-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
